[package]
name = "log-example"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = {version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
tracing = "0.1"
tracing-subscriber = "0.3"
